### ISSUE TITLE
bug: KeyError: 'current_UA_code'

### ISSUE THREAD

**Issue by msramalho** [jclark1913/osint-google-analytics#17]
```
wayback_google_analytics/output.py", line 101, in get_urls_df
    "UA_Code": info["current_UA_code"],
KeyError: 'current_UA_code'
```
This is due, I believe, to [this code section](https://github.com/bellingcat/wayback-google-analytics/blob/5af4b46e0b71fe26605417fa2fe6409c231bef28/wayback_google_analytics/scraper.py#L84-L88) where the keys are assigned, but only if the `html` variable is not None.

One simple solution is to do dict.get instead of dict[] for the optionally present parameters, eg: `info.get("current_UA_code", "")`, but I wonder if there's some missing logic between the 2 different parts and if there's a better way to address it.

**Comment by jclark1913** [comment]
Resolved in PR #18.
