### ISSUE TITLE
Output File Naming Issue on Windows Leads to OSError

### ISSUE THREAD

**Issue by martyna1221** [jclark1913/osint-google-analytics#26]
When attempting to run wayback-google-analytics with the --output json option on Windows, the program fails during the output file generation phase, raising an OSError related to an invalid argument in the file path. This issue appears to be caused by the inclusion of characters in the automatically generated file name that are not allowed in Windows file paths (e.g., :).

### **Steps to Reproduce:**
Execute the command with the following parameters:
`wayback-google-analytics --urls https://someurl.com https://otherurl.org --output json --start_date 01/10/2012 --end_date 25/10/2012 --frequency hourly`

The command fails after processing with an OSError regarding an invalid file name argument.

The execution fails with the following error:
`OSError: [Errno 22] Invalid argument: './output\\16-02-2024(15:38:18).json'`

### **Additional Information:**
- Operating System: Windows
- Python Version: 3.11.8
- Tool Version: 0.2.2

Ciao!

**Comment by jclark1913** [comment]
Thanks for finding this issue, @martyna1221 ! Extra thanks for being so clear in your issue writeup. 

This is an oversight on my part - some of the file paths generated in [output.py](https://github.com/bellingcat/wayback-google-analytics/blob/main/wayback_google_analytics/output.py) aren't very inclusive of Windows users. 

I'll take some time this evening to look through the code and hopefully get a fix out soon.

**Comment by martyna1221** [comment]
Hi!

Replacing ln. 29 with this `file_name = datetime.now().strftime("%d-%m-%Y_%H-%M-%S")` fixed the issue. 

Thanks!
